#! /bin/sh

# Copyright (C) 2025 PLAYThe218
# Author: playthe218 <playthe218@icloud.com>

# This script is released under MIT License.
# See LICENSE file in the project root for full license terms.

# Update grub.cfg.

# This script will assume the boot directory is at /boot and grub.cfg is at /boot/grub/grub.cfg.

BOOT_DIR=/boot

if [[ $EUID -ne 0 ]]; then
	echo -e "[\e[31m!\e[0m] error: Unable to proceed: Are you root?"
	exit 1
fi

if [[ ! -f "/usr/bin/grub-mkconfig" ]]; then
	echo -e "[\e[31m!\e[0m] error: Unable to proceed: Have you installed GRUB?"
	exit 1
fi

LANG="en_US.UTF-8" grub-mkconfig -o $BOOT_DIR/grub/grub.cfg

echo -e "[\e[34m*\e[0m] GRUB config update completed."
