#! /bin/sh

# Copyright (C) 2025 PLAYThe218
# Author: playthe218 <playthe218@icloud.com>

# Update grub config.

# This script will assume the boot directory is at /boot and grub.cfg is at /boot/grub/grub.cfg.

if [[ $EUID -ne 0 ]]; then
	echo -e "[\e[31m!\e[0m] Can not continue since you are not root!"
	exit 1
fi

LANG="en_US.UTF-8" grub-mkconfig -o /boot/grub/grub.cfg

echo -e "[\e[34m*\e[0m] GRUB config update completed."
